package dev.bsbedwars.it.shop.content.items.special.tower.component.coord;

import lombok.Getter;

import java.util.ArrayList;
import java.util.List;


public class TowerStatus {

    @Getter
    private static final List<String> rellocNord = new ArrayList<>();
    @Getter
    private static final List<String> rellocSud = new ArrayList<>();
    @Getter
    private static final List<String> rellocEst = new ArrayList<>();
    @Getter
    private static final List<String> rellocOvest = new ArrayList<>();


    static {
        // est
        rellocEst.add("2, 0, -1");
        rellocEst.add("1, 0, -2");
        rellocEst.add("0, 0, -2");
        rellocEst.add("-1, 0, -1");
        rellocEst.add("-1, 0, 0");
        rellocEst.add("-1, 0, 1");
        rellocEst.add("0, 0, 2");
        rellocEst.add("1, 0, 2");
        rellocEst.add("2, 0, 1");
        rellocEst.add("0, 0, 0, ladder5");
        rellocEst.add("2, 1, -1");
        rellocEst.add("1, 1, -2");
        rellocEst.add("0, 1, -2");
        rellocEst.add("-1, 1, -1");
        rellocEst.add("-1, 1, 0");
        rellocEst.add("-1, 1, 1");
        rellocEst.add("0, 1, 2");
        rellocEst.add("1, 1, 2");
        rellocEst.add("2, 1, 1");
        rellocEst.add("0, 1, 0, ladder5");
        rellocEst.add("2, 2, -1");
        rellocEst.add("1, 2, -2");
        rellocEst.add("0, 2, -2");
        rellocEst.add("-1, 2, -1");
        rellocEst.add("-1, 2, 0");
        rellocEst.add("-1, 2, 1");
        rellocEst.add("0, 2, 2");
        rellocEst.add("1, 2, 2");
        rellocEst.add("2, 2, 1");
        rellocEst.add("0, 2, 0, ladder5");
        rellocEst.add("2, 3, 0");
        rellocEst.add("2, 3, -1");
        rellocEst.add("1, 3, -2");
        rellocEst.add("0, 3, -2");
        rellocEst.add("-1, 3, -1");
        rellocEst.add("-1, 3, 0");
        rellocEst.add("-1, 3, 1");
        rellocEst.add("0, 3, 2");
        rellocEst.add("1, 3, 2");
        rellocEst.add("2, 3, 1");
        rellocEst.add("0, 3, 0, ladder5");
        rellocEst.add("2, 4, 0");
        rellocEst.add("2, 4, -1");
        rellocEst.add("1, 4, -2");
        rellocEst.add("0, 4, -2");
        rellocEst.add("-1, 4, -1");
        rellocEst.add("-1, 4, 0");
        rellocEst.add("-1, 4, 1");
        rellocEst.add("0, 4, 2");
        rellocEst.add("1, 4, 2");
        rellocEst.add("2, 4, 1");
        rellocEst.add("0, 4, 0, ladder5");
        rellocEst.add("-1, 5, -2");
        rellocEst.add("0, 5, -2");
        rellocEst.add("1, 5, -2");
        rellocEst.add("2, 5, -2");
        rellocEst.add("-1, 5, -1");
        rellocEst.add("0, 5, -1");
        rellocEst.add("1, 5, -1");
        rellocEst.add("2, 5, -1");
        rellocEst.add("-1, 5, 0");
        rellocEst.add("1, 5, 0");
        rellocEst.add("2, 5, 0");
        rellocEst.add("-1, 5, 1");
        rellocEst.add("0, 5, 0, ladder5");
        rellocEst.add("0, 5, 1");
        rellocEst.add("1, 5, 1");
        rellocEst.add("2, 5, 1");
        rellocEst.add("-1, 5, 2");
        rellocEst.add("0, 5, 2");
        rellocEst.add("1, 5, 2");
        rellocEst.add("2, 5, 2");
        rellocEst.add("2, 5, -3");
        rellocEst.add("2, 6, -3");
        rellocEst.add("2, 7, -3");
        rellocEst.add("1, 6, -3");
        rellocEst.add("0, 6, -3");
        rellocEst.add("-1, 5, -3");
        rellocEst.add("-1, 6, -3");
        rellocEst.add("-1, 7, -3");
        rellocEst.add("-2, 5, -2");
        rellocEst.add("-2, 6, -2");
        rellocEst.add("-2, 7, -2");
        rellocEst.add("-2, 6, -1");
        rellocEst.add("-2, 5, 0");
        rellocEst.add("-2, 6, 0");
        rellocEst.add("-2, 7, 0");
        rellocEst.add("-2, 6, 1");
        rellocEst.add("-2, 5, 2");
        rellocEst.add("-2, 6, 2");
        rellocEst.add("-2, 7, 2");
        rellocEst.add("2, 5, 3");
        rellocEst.add("2, 6, 3");
        rellocEst.add("2, 7, 3");
        rellocEst.add("1, 6, 3");
        rellocEst.add("0, 6, 3");
        rellocEst.add("-1, 5, 3");
        rellocEst.add("-1, 6, 3");
        rellocEst.add("-1, 7, 3");
        rellocEst.add("3, 5, -2");
        rellocEst.add("3, 6, -2");
        rellocEst.add("3, 7, -2");
        rellocEst.add("3, 6, -1");
        rellocEst.add("3, 5, 0");
        rellocEst.add("3, 6, 0");
        rellocEst.add("3, 7, 0");
        rellocEst.add("3, 6, 1");
        rellocEst.add("3, 5, 2");
        rellocEst.add("3, 6, 2");
        rellocEst.add("3, 7, 2");
        // nord
        rellocNord.add("-1, 0, -2");
        rellocNord.add("-2, 0, -1");
        rellocNord.add("-2, 0, 0");
        rellocNord.add("-1, 0, 1");
        rellocNord.add("0, 0, 1");
        rellocNord.add("1, 0, 1");
        rellocNord.add("2, 0, 0");
        rellocNord.add("2, 0, -1");
        rellocNord.add("1, 0, -2");
        rellocNord.add("0, 0, 0, ladder2");
        rellocNord.add("-1, 1, -2");
        rellocNord.add("-2, 1, -1");
        rellocNord.add("-2, 1, 0");
        rellocNord.add("-1, 1, 1");
        rellocNord.add("0, 1, 1");
        rellocNord.add("1, 1, 1");
        rellocNord.add("2, 1, 0");
        rellocNord.add("2, 1, -1");
        rellocNord.add("1, 1, -2");
        rellocNord.add("0, 1, 0, ladder2");
        rellocNord.add("-1, 2, -2");
        rellocNord.add("-2, 2, -1");
        rellocNord.add("-2, 2, 0");
        rellocNord.add("-1, 2, 1");
        rellocNord.add("0, 2, 1");
        rellocNord.add("1, 2, 1");
        rellocNord.add("2, 2, 0");
        rellocNord.add("2, 2, -1");
        rellocNord.add("1, 2, -2");
        rellocNord.add("0, 2, 0, ladder2");
        rellocNord.add("0, 3, -2");
        rellocNord.add("-1, 3, -2");
        rellocNord.add("-2, 3, -1");
        rellocNord.add("-2, 3, 0");
        rellocNord.add("-1, 3, 1");
        rellocNord.add("0, 3, 1");
        rellocNord.add("1, 3, 1");
        rellocNord.add("2, 3, 0");
        rellocNord.add("2, 3, -1");
        rellocNord.add("1, 3, -2");
        rellocNord.add("0, 3, 0, ladder2");
        rellocNord.add("0, 4, -2");
        rellocNord.add("-1, 4, -2");
        rellocNord.add("-2, 4, -1");
        rellocNord.add("-2, 4, 0");
        rellocNord.add("-1, 4, 1");
        rellocNord.add("0, 4, 1");
        rellocNord.add("1, 4, 1");
        rellocNord.add("2, 4, 0");
        rellocNord.add("2, 4, -1");
        rellocNord.add("1, 4, -2");
        rellocNord.add("0, 4, 0, ladder2");
        rellocNord.add("-2, 5, 1");
        rellocNord.add("-2, 5, 0");
        rellocNord.add("-2, 5, -1");
        rellocNord.add("-2, 5, -2");
        rellocNord.add("-1, 5, 1");
        rellocNord.add("-1, 5, 0");
        rellocNord.add("-1, 5, -1");
        rellocNord.add("-1, 5, -2");
        rellocNord.add("0, 5, 1");
        rellocNord.add("0, 5, -1");
        rellocNord.add("0, 5, -2");
        rellocNord.add("1, 5, 1");
        rellocNord.add("0, 5, 0, ladder2");
        rellocNord.add("1, 5, 0");
        rellocNord.add("1, 5, -1");
        rellocNord.add("1, 5, -2");
        rellocNord.add("2, 5, 1");
        rellocNord.add("2, 5, 0");
        rellocNord.add("2, 5, -1");
        rellocNord.add("2, 5, -2");
        rellocNord.add("-3, 5, -2");
        rellocNord.add("-3, 6, -2");
        rellocNord.add("-3, 7, -2");
        rellocNord.add("-3, 6, -1");
        rellocNord.add("-3, 6, 0");
        rellocNord.add("-3, 5, 1");
        rellocNord.add("-3, 6, 1");
        rellocNord.add("-3, 7, 1");
        rellocNord.add("-2, 5, 2");
        rellocNord.add("-2, 6, 2");
        rellocNord.add("-2, 7, 2");
        rellocNord.add("-1, 6, 2");
        rellocNord.add("0, 5, 2");
        rellocNord.add("0, 6, 2");
        rellocNord.add("0, 7, 2");
        rellocNord.add("1, 6, 2");
        rellocNord.add("2, 5, 2");
        rellocNord.add("2, 6, 2");
        rellocNord.add("2, 7, 2");
        rellocNord.add("3, 5, -2");
        rellocNord.add("3, 6, -2");
        rellocNord.add("3, 7, -2");
        rellocNord.add("3, 6, -1");
        rellocNord.add("3, 6, 0");
        rellocNord.add("3, 5, 1");
        rellocNord.add("3, 6, 1");
        rellocNord.add("3, 7, 1");
        rellocNord.add("-2, 5, -3");
        rellocNord.add("-2, 6, -3");
        rellocNord.add("-2, 7, -3");
        rellocNord.add("-1, 6, -3");
        rellocNord.add("0, 5, -3");
        rellocNord.add("0, 6, -3");
        rellocNord.add("0, 7, -3");
        rellocNord.add("1, 6, -3");
        rellocNord.add("2, 5, -3");
        rellocNord.add("2, 6, -3");
        rellocNord.add("2, 7, -3");
        // sud
        rellocSud.add("1, 0, 2");
        rellocSud.add("2, 0, 1");
        rellocSud.add("2, 0, 0");
        rellocSud.add("1, 0, -1");
        rellocSud.add("0, 0, -1");
        rellocSud.add("-1, 0, -1");
        rellocSud.add("-2, 0, 0");
        rellocSud.add("-2, 0, 1");
        rellocSud.add("-1, 0, 2");
        rellocSud.add("0, 0, 0, ladder3");
        rellocSud.add("1, 1, 2");
        rellocSud.add("2, 1, 1");
        rellocSud.add("2, 1, 0");
        rellocSud.add("1, 1, -1");
        rellocSud.add("0, 1, -1");
        rellocSud.add("-1, 1, -1");
        rellocSud.add("-2, 1, 0");
        rellocSud.add("-2, 1, 1");
        rellocSud.add("-1, 1, 2");
        rellocSud.add("0, 1, 0, ladder3");
        rellocSud.add("1, 2, 2");
        rellocSud.add("2, 2, 1");
        rellocSud.add("2, 2, 0");
        rellocSud.add("1, 2, -1");
        rellocSud.add("0, 2, -1");
        rellocSud.add("-1, 2, -1");
        rellocSud.add("-2, 2, 0");
        rellocSud.add("-2, 2, 1");
        rellocSud.add("-1, 2, 2");
        rellocSud.add("0, 2, 0, ladder3");
        rellocSud.add("0, 3, 2");
        rellocSud.add("1, 3, 2");
        rellocSud.add("2, 3, 1");
        rellocSud.add("2, 3, 0");
        rellocSud.add("1, 3, -1");
        rellocSud.add("0, 3, -1");
        rellocSud.add("-1, 3, -1");
        rellocSud.add("-2, 3, 0");
        rellocSud.add("-2, 3, 1");
        rellocSud.add("-1, 3, 2");
        rellocSud.add("0, 3, 0, ladder3");
        rellocSud.add("0, 4, 2");
        rellocSud.add("1, 4, 2");
        rellocSud.add("2, 4, 1");
        rellocSud.add("2, 4, 0");
        rellocSud.add("1, 4, -1");
        rellocSud.add("0, 4, -1");
        rellocSud.add("-1, 4, -1");
        rellocSud.add("-2, 4, 0");
        rellocSud.add("-2, 4, 1");
        rellocSud.add("-1, 4, 2");
        rellocSud.add("0, 4, 0, ladder3");
        rellocSud.add("2, 5, -1");
        rellocSud.add("2, 5, 0");
        rellocSud.add("2, 5, 1");
        rellocSud.add("2, 5, 2");
        rellocSud.add("1, 5, -1");
        rellocSud.add("1, 5, 0");
        rellocSud.add("1, 5, 1");
        rellocSud.add("1, 5, 2");
        rellocSud.add("0, 5, -1");
        rellocSud.add("0, 5, 1");
        rellocSud.add("0, 5, 2");
        rellocSud.add("-1, 5, -1");
        rellocSud.add("0, 5, 0, ladder3");
        rellocSud.add("-1, 5, 0");
        rellocSud.add("-1, 5, 1");
        rellocSud.add("-1, 5, 2");
        rellocSud.add("-2, 5, -1");
        rellocSud.add("-2, 5, 0");
        rellocSud.add("-2, 5, 1");
        rellocSud.add("-2, 5, 2");
        rellocSud.add("3, 5, 2");
        rellocSud.add("3, 6, 2");
        rellocSud.add("3, 7, 2");
        rellocSud.add("3, 6, 1");
        rellocSud.add("3, 6, 0");
        rellocSud.add("3, 5, -1");
        rellocSud.add("3, 6, -1");
        rellocSud.add("3, 7, -1");
        rellocSud.add("2, 5, -2");
        rellocSud.add("2, 6, -2");
        rellocSud.add("2, 7, -2");
        rellocSud.add("1, 6, -2");
        rellocSud.add("0, 5, -2");
        rellocSud.add("0, 6, -2");
        rellocSud.add("0, 7, -2");
        rellocSud.add("-1, 6, -2");
        rellocSud.add("-2, 5, -2");
        rellocSud.add("-2, 6, -2");
        rellocSud.add("-2, 7, -2");
        rellocSud.add("-3, 5, 2");
        rellocSud.add("-3, 6, 2");
        rellocSud.add("-3, 7, 2");
        rellocSud.add("-3, 6, 1");
        rellocSud.add("-3, 6, 0");
        rellocSud.add("-3, 5, -1");
        rellocSud.add("-3, 6, -1");
        rellocSud.add("-3, 7, -1");
        rellocSud.add("2, 5, 3");
        rellocSud.add("2, 6, 3");
        rellocSud.add("2, 7, 3");
        rellocSud.add("1, 6, 3");
        rellocSud.add("0, 5, 3");
        rellocSud.add("0, 6, 3");
        rellocSud.add("0, 7, 3");
        rellocSud.add("-1, 6, 3");
        rellocSud.add("-2, 5, 3");
        rellocSud.add("-2, 6, 3");
        rellocSud.add("-2, 7, 3");
        // ovest
        rellocOvest.add("-2, 0, 1");
        rellocOvest.add("-1, 0, 2");
        rellocOvest.add("0, 0, 2");
        rellocOvest.add("1, 0, 1");
        rellocOvest.add("1, 0, 0");
        rellocOvest.add("1, 0, -1");
        rellocOvest.add("0, 0, -2");
        rellocOvest.add("-1, 0, -2");
        rellocOvest.add("-2, 0, -1");
        rellocOvest.add("0, 0, 0, ladder4");
        rellocOvest.add("-2, 1, 1");
        rellocOvest.add("-1, 1, 2");
        rellocOvest.add("0, 1, 2");
        rellocOvest.add("1, 1, 1");
        rellocOvest.add("1, 1, 0");
        rellocOvest.add("1, 1, -1");
        rellocOvest.add("0, 1, -2");
        rellocOvest.add("-1, 1, -2");
        rellocOvest.add("-2, 1, -1");
        rellocOvest.add("0, 1, 0, ladder4");
        rellocOvest.add("-2, 2, 1");
        rellocOvest.add("-1, 2, 2");
        rellocOvest.add("0, 2, 2");
        rellocOvest.add("1, 2, 1");
        rellocOvest.add("1, 2, 0");
        rellocOvest.add("1, 2, -1");
        rellocOvest.add("0, 2, -2");
        rellocOvest.add("-1, 2, -2");
        rellocOvest.add("-2, 2, -1");
        rellocOvest.add("0, 2, 0, ladder4");
        rellocOvest.add("-2, 3, 0");
        rellocOvest.add("-2, 3, 1");
        rellocOvest.add("-1, 3, 2");
        rellocOvest.add("0, 3, 2");
        rellocOvest.add("1, 3, 1");
        rellocOvest.add("1, 3, 0");
        rellocOvest.add("1, 3, -1");
        rellocOvest.add("0, 3, -2");
        rellocOvest.add("-1, 3, -2");
        rellocOvest.add("-2, 3, -1");
        rellocOvest.add("0, 3, 0, ladder4");
        rellocOvest.add("-2, 4, 0");
        rellocOvest.add("-2, 4, 1");
        rellocOvest.add("-1, 4, 2");
        rellocOvest.add("0, 4, 2");
        rellocOvest.add("1, 4, 1");
        rellocOvest.add("1, 4, 0");
        rellocOvest.add("1, 4, -1");
        rellocOvest.add("0, 4, -2");
        rellocOvest.add("-1, 4, -2");
        rellocOvest.add("-2, 4, -1");
        rellocOvest.add("0, 4, 0, ladder4");
        rellocOvest.add("1, 5, 2");
        rellocOvest.add("0, 5, 2");
        rellocOvest.add("-1, 5, 2");
        rellocOvest.add("-2, 5, 2");
        rellocOvest.add("1, 5, 1");
        rellocOvest.add("0, 5, 1");
        rellocOvest.add("-1, 5, 1");
        rellocOvest.add("-2, 5, 1");
        rellocOvest.add("1, 5, 0");
        rellocOvest.add("-1, 5, 0");
        rellocOvest.add("-2, 5, 0");
        rellocOvest.add("1, 5, -1");
        rellocOvest.add("0, 5, -1");
        rellocOvest.add("-1, 5, -1");
        rellocOvest.add("-2, 5, -1");
        rellocOvest.add("0, 5, 0, ladder4");
        rellocOvest.add("1, 5, -2");
        rellocOvest.add("0, 5, -2");
        rellocOvest.add("-1, 5, -2");
        rellocOvest.add("-2, 5, -2");
        rellocOvest.add("-2, 5, 3");
        rellocOvest.add("-2, 6, 3");
        rellocOvest.add("-2, 7, 3");
        rellocOvest.add("-1, 6, 3");
        rellocOvest.add("0, 6, 3");
        rellocOvest.add("1, 5, 3");
        rellocOvest.add("1, 6, 3");
        rellocOvest.add("1, 7, 3");
        rellocOvest.add("2, 5, 2");
        rellocOvest.add("2, 6, 2");
        rellocOvest.add("2, 7, 2");
        rellocOvest.add("2, 6, 1");
        rellocOvest.add("2, 5, 0");
        rellocOvest.add("2, 6, 0");
        rellocOvest.add("2, 7, 0");
        rellocOvest.add("2, 6, -1");
        rellocOvest.add("2, 5, -2");
        rellocOvest.add("2, 6, -2");
        rellocOvest.add("2, 7, -2");
        rellocOvest.add("-2, 5, -3");
        rellocOvest.add("-2, 6, -3");
        rellocOvest.add("-2, 7, -3");
        rellocOvest.add("-1, 6, -3");
        rellocOvest.add("0, 6, -3");
        rellocOvest.add("1, 5, -3");
        rellocOvest.add("1, 6, -3");
        rellocOvest.add("1, 7, -3");
        rellocOvest.add("-3, 5, 2");
        rellocOvest.add("-3, 6, 2");
        rellocOvest.add("-3, 7, 2");
        rellocOvest.add("-3, 6, 1");
        rellocOvest.add("-3, 5, 0");
        rellocOvest.add("-3, 6, 0");
        rellocOvest.add("-3, 7, 0");
        rellocOvest.add("-3, 6, -1");
        rellocOvest.add("-3, 5, -2");
        rellocOvest.add("-3, 6, -2");
        rellocOvest.add("-3, 7, -2");
    }

    public enum Type {
        NORTH,
        SOUTH,
        WEST,
        EST;
    }
    
}
